name: Victor´s app
description: Management application for entrepreneurs.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
fonts:
  - family: 
   fonts:
     - asset: fonts/-Regular.ttf
